// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8gYsXaBnsPS4GuuN4o7TsUvcsYVozXUI',
    appId: '1:657818941322:web:e8c7177af037ae6bf2fa73',
    messagingSenderId: '657818941322',
    projectId: 'artpro-8f549',
    authDomain: 'artpro-8f549.firebaseapp.com',
    storageBucket: 'artpro-8f549.appspot.com',
    measurementId: 'G-8H8CTP5TPX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPvgrcSCNCbOpLmKH5jlGSuUgrV1RA2Ck',
    appId: '1:657818941322:android:0f7c9c393f8c0f11f2fa73',
    messagingSenderId: '657818941322',
    projectId: 'artpro-8f549',
    storageBucket: 'artpro-8f549.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeTSBni-Qxp__iU2juwhJ4mwVxEFceMP8',
    appId: '1:657818941322:ios:88c9485fe79db554f2fa73',
    messagingSenderId: '657818941322',
    projectId: 'artpro-8f549',
    storageBucket: 'artpro-8f549.appspot.com',
    iosClientId: '657818941322-rca8nnl34voens8qsufg6krm7999o0ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.artproApplicationNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeTSBni-Qxp__iU2juwhJ4mwVxEFceMP8',
    appId: '1:657818941322:ios:88c9485fe79db554f2fa73',
    messagingSenderId: '657818941322',
    projectId: 'artpro-8f549',
    storageBucket: 'artpro-8f549.appspot.com',
    iosClientId: '657818941322-rca8nnl34voens8qsufg6krm7999o0ni.apps.googleusercontent.com',
    iosBundleId: 'com.example.artproApplicationNew',
  );
}
